# Generated by Django 4.2.9 on 2024-01-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desription',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
