# Generated by Django 4.2.9 on 2024-01-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0002_alter_products_desription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='desription',
            new_name='description',
        ),
    ]
