# Generated by Django 4.2.9 on 2024-01-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0003_rename_desription_products_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product']},
        ),
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='updated_at',
        ),
    ]
